Number 1

In [6]:
import numpy as np 
a = np.array([[4, -2, 1], [3, 6, -4], [2, 1, 8]])
print (a)

[[ 4 -2  1]
 [ 3  6 -4]
 [ 2  1  8]]


In [8]:
from numpy.linalg import inv
np.dot (inv(a), a)

array([[ 1.00000000e+00, -3.46944695e-18,  5.55111512e-17],
       [ 8.32667268e-17,  1.00000000e+00,  1.11022302e-16],
       [ 2.77555756e-17,  1.38777878e-17,  1.00000000e+00]])

In [10]:
np.dot (a, inv(a))

array([[ 1.00000000e+00, -2.08166817e-17,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00, -2.77555756e-17,  1.00000000e+00]])

In [12]:
inv(a)

array([[ 0.19771863,  0.06463878,  0.00760456],
       [-0.121673  ,  0.11406844,  0.07224335],
       [-0.03422053, -0.03041825,  0.11406844]])

Number 2

In [16]:
import numpy as np 
a = np.array([[4, -2, 1], [3, 6, -4], [2, 1, 8]])
print (a)

[[ 4 -2  1]
 [ 3  6 -4]
 [ 2  1  8]]


In [18]:
b1 = np.array([12, -25, 32])
print (b1)

[ 12 -25  32]


In [20]:
from numpy.linalg import solve
x1= solve (a, b1)
print (x1)

[ 1. -2.  4.]


In [24]:
b2 = np.array([4, -10, 22])
x2 = solve (a, b2)
print (x2)

[ 0.31178707 -0.03802281  2.67680608]


In [26]:
b3 = np.array ([20, -30, 40])
x3 = solve (a, b3)
print (x3)

[ 2.31939163 -2.96577947  4.79087452]


Number 3

In [29]:
import sympy as sp
x = sp.symbols('x')
b = sp.tan(x)
sp.diff(b, x)

tan(x)**2 + 1

Number 4

In [32]:
import sympy as sp
x = sp.symbols('x')
A = sp.sin(x)
A.series (x, 10)

sin(10) + (x - 10)*cos(10) - (x - 10)**2*sin(10)/2 - (x - 10)**3*cos(10)/6 + (x - 10)**4*sin(10)/24 + (x - 10)**5*cos(10)/120 + O((x - 10)**6, (x, 10))

Number 5

In [41]:
import sympy as sp 
x = sp.symbols('x')
b = sp.tan (x)**2
sp.simplify(1+b)

cos(x)**(-2)